services:
  ntfy:
    image: binwiederhier/ntfy
    restart: unless-stopped
    environment:
      NTFY_AUTH_DEFAULT_ACCESS: "deny-all"
      NTFY_DATABASE_URL: ${POSTGRES_URL}
    ports:
      - 80
    configs:
      - source: temps_yml
        target: /etc/ntfy/templates/temps.yml
    command: serve

configs:
  temps_yml:
    file: ./templates/temps.yml
