services:
  ntfy:
    image: binwiederhier/ntfy
    restart: unless-stopped
    environment:
      NTFY_AUTH_DEFAULT_ACCESS: "deny-all"
      NTFY_DATABASE_URL: ${POSTGRES_URL}
    ports:
      - 80
    command: serve
